//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace notasEstudiantes.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class materia
    {
        public int id_materia { get; set; }
        public string nombre_materia { get; set; }
    }
}
